Console.WriteLine("How many miles is the trip both ways? ");
double milesForTheTrip = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("What is the miles per gallon of the car during the trip? ");
double milesPerGallon = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("How much is the Price per gallon of gas? ");
double price = Convert.ToDouble(Console.ReadLine());
double gallonsNeeded = milesForTheTrip/milesPerGallon;
double fuelCost = gallonsNeeded * price;
Console.WriteLine("Gallons needed: " + gallonsNeeded.ToString("F2"));
Console.WriteLine("Fuel cost: " + fuelCost.ToString("C"));

Console.WriteLine("How many people are going to be there? ");
double peopleCount = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("How many pizzas are needed? ");
int pizzaCount = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("How much does a pizza cost? ");
double pizzaPrice = Convert.ToDouble(Console.ReadLine());
const int NUMBERS_OF_SLICES = 8;
double totalSlices = pizzaCount * NUMBERS_OF_SLICES;
double slicesPerPerson = totalSlices/peopleCount;
double pizzaCost = pizzaCount * pizzaPrice;
Console.WriteLine ("Total slices: " + totalSlices);
Console.WriteLine("Slices per person: " + slicesPerPerson.ToString("F1"));
Console.WriteLine("Pizza cost: " + pizzaCost.ToString("C"));

Console.WriteLine("How many hours did you worked this week? ");
double hoursWorked = Convert.ToDouble(Console.ReadLine());
Console.WriteLine("What is the hourly rate? ");
double hourlyRate = Convert.ToDouble(Console.ReadLine());
const double TAX_RATE = .18;
double grossPay = hourlyRate * hoursWorked;
double taxWithheld = grossPay * TAX_RATE;
double takeHome = grossPay - taxWithheld;
Console.WriteLine("Gross pay: " + grossPay.ToString("C"));
Console.WriteLine("Tax withheld: " + taxWithheld.ToString("C"));
Console.WriteLine("Take home pay: " + takeHome.ToString("C"));